'use strict';var JSOX="object"===typeof exports?exports:{};
function privateizeEverything(){function ha(){var c=T.pop();c||(c={context:0,current_class:null,current_class_field:0,arrayType:-1,elements:null,element_array:null});return c}function la(){var c=ia.pop();c?c.n=0:c={buf:null,n:0};return c}function ma(c){var p="";c=new Uint8Array(c);var a=c.byteLength,n=a%3;a-=n;for(var h,g,b,d,e=0;e<a;e+=3)d=c[e]<<16|c[e+1]<<8|c[e+2],h=(d&16515072)>>18,g=(d&258048)>>12,b=(d&4032)>>6,d&=63,p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g]+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[b]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d];1==n?(d=c[a],h=(d&252)>>2,g=(d&3)<<4,p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g]+"=="):2==n&&(d=c[a]<<8|c[a+1],h=(d&64512)>>10,g=(d&1008)>>4,b=(d&15)<<2,p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g]+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[b]+"=");return p}function na(c){var p=new ArrayBuffer(3*(c.length+3>>2|0)-(("="===c[c.length-1]?1:0)+("="===c[c.length-2]?1:0))),a=new Uint8Array(p),n,h=c.length+3>>2;for(n=0;n<h;n++){var g=M[c[4*n+1]],b=M[c[4*n+2]],d=M[c[4*n+3]];a[3*n]=M[c[4*n]]<<2|g>>4;0<=b&&(a[3*n+1]=g<<4|b>>2&15);0<=d&&(a[3*n+2]=b<<6|d&63)}return p}const oa="ab u8 cu8 s8 u16 s16 u32 s32 u64 s64 f32 f64".split(" "),pa=[ArrayBuffer,Uint8Array,Uint8ClampedArray,Int8Array,
Uint16Array,Int16Array,Uint32Array,Int32Array,null,null,Float32Array,Float32Array],T=[],ia=[];JSOX.escape=function(c){var p,a="";if(!c)return c;for(p=0;p<c.length;p++){if('"'==c[p]||"\\"==c[p]||"`"==c[p]||"'"==c[p])a+="\\";a+=c[p]}return a};JSOX.begin=function(c,p){const a={name:null,value_type:0,string:"",contains:null},n={line:1,col:1};let h=0,g;var b=0,d=!0,e=!1,D=null,P=null,y=void 0,q=[],v={first:null,last:null,saved:null,push(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=null,b.prior=
this.last):b={node:a,next:null,prior:this.last};this.last||(this.first=b);this.last=b;this.length++},pop(){var a=this.last;if(!a)return null;(this.last=a.prior)||(this.first=null);a.next=this.saved;this.saved=a;this.length--;return a.node},length:0},u=[],K={},w=null,F=0,G=-1,k=0,x=0,l=!1,r=!1,m=!1,aa=!1,ba=!1,I={first:null,last:null,saved:null,push(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=null,b.prior=this.last):b={node:a,next:null,prior:this.last};this.last||(this.first=b);this.last=
b},shift(){var a=this.first;if(!a)return null;(this.first=a.next)||(this.last=null);a.next=this.saved;this.saved=a;return a.node},unshift(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=this.first,b.prior=null):b={node:a,next:this.first,prior:null};this.first||(this.last=b);this.first=b}},M=null,Q=!1,R=!1,B=!1,ca=!1,U=!1,N=!1,V=!1,z=0,H=0,W=!1,E=!1,J=!1,X=!1;return{value(){var a=D;D=void 0;return a},reset(){b=0;d=!0;I.last&&(I.last.next=I.save);I.save=I.first;I.first=I.last=null;v.last&&
(v.last.next=v.save);v.save=I.first;q=v.first=v.last=null;y=void 0;k=0;u=[];K={};w=null;F=0;a.value_type=0;a.name=null;a.string="";n.line=1;n.col=1;e=!1;x=0;ca=B=Q=E=!1},usePrototype(a,b){K[a]=b},write(a){"string"!==typeof a&&(a=String(a));for(a=this._write(a,!1);0<a&&!(D&&("function"===typeof p&&function ra(a,b){var d,c=a[b];if(c&&"object"===typeof c)for(d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var k=ra(c,d);void 0!==k?c[d]=k:delete c[d]}return p.call(a,b,c)}({"":D},""),c(D),D=void 0),
2>a);a=this._write());},_write(c,p){function t(a,b){throw Error(`${a} '${String.fromCodePoint(b)}' unexpected at ${h} (near '${C.substr(4<h?h-4:0,4<h?3:h-1)}[${String.fromCodePoint(b)}]${C.substr(h,10)}') [${n.line}:${n.col}]`);}function O(){a.value_type=0;a.string=""}function qa(a){return X?BigInt(a):J?new Date(a):1<a.length&&!l&&!r&&!m&&48===a.charCodeAt(0)?(e?-1:1)*Number("0o"+a):(e?-1:1)*Number(a)}function da(){switch(a.value_type){case 5:return X?BigInt(a.string):J?new Date(a.string):qa(a.string);
case 4:return a.string;case 2:return!0;case 3:return!1;case 7:return NaN;case 8:return NaN;case 9:return-Infinity;case 10:return Infinity;case 1:return null;case -1:break;case 12:break;case 6:return a.contains;case 13:if(0<=G){var b=na(a.string);return 0===G?b:new pa[G](b)}if(-2===G){var c=P;a.contains.forEach((a)=>c=c[a]);return c}return a.contains;default:console.log("Unhandled value conversion.",a)}}function S(){switch(a.value_type){case 12:q.push(void 0);delete q[q.length-1];break;default:q.push(da())}}
function Y(){12!==a.value_type&&(y[a.name]=da())}function A(c){e&&(valstring+="-",e=!1);switch(b){case 31:switch(a.value_type){case 2:a.string+="true";break;case 3:a.string+="false";break;case 1:a.string+="null";break;case 10:a.string+="Infinity";break;case 9:a.string+="-Infinity";break;case 8:a.string+="NaN";break;case 7:a.string+="-NaN";break;case -1:a.string+="undefined";break;default:console.log("Value of type "+a.value_type+" is not restored...")}case 1:a.string+="t";break;case 2:a.string+="tr";
break;case 3:a.string+="tru";break;case 5:a.string+="f";break;case 6:a.string+="fa";break;case 7:a.string+="fal";break;case 8:a.string+="fals";break;case 9:a.string+="n";break;case 10:a.string+="nu";break;case 11:a.string+="nul";break;case 12:a.string+="u";break;case 13:a.string+="un";break;case 14:a.string+="und";break;case 15:a.string+="unde";break;case 16:a.string+="undef";break;case 17:a.string+="undefi";break;case 18:a.string+="undefin";break;case 19:a.string+="undefine";break;case 20:a.string+=
"Ma";break;case 21:a.string+="NaN";break;case 22:a.string+="I";break;case 23:a.string+="In";break;case 24:a.string+="Inf";break;case 25:a.string+="Infi";break;case 26:a.string+="Infin";break;case 27:a.string+="Infini";break;case 28:a.string+="Infinit"}b=29;123==c?ja():91==c?ka():32!=c&&13!=c&&10!=c&&9!=c&&65279!=c&&(44==c||125==c||93==c||58==c?t("Invalid character near identifier",c):a.string+=g)}function ea(b){let c=0;for(;0==c&&h<C.length;){g=C.charAt(h);let d=C.codePointAt(h++);65536<=d&&(g+=C.charAt(h),
h++);n.col++;if(d==b)B?(a.string+=g,B=!1):(W?t("Incomplete Octal sequence",d):V?t("Incomplete hexidecimal sequence",d):N?t("Incomplete unicode sequence",d):U&&t("Incomplete long unicode sequence",d),c=1);else if(B)if(W)if(3>H&&48<=d&&57>=d)z*=8,z+=d-48,H++,3===H&&(a.string+=String.fromCodePoint(z),B=W=!1);else{if(255<z){t("(escaped character, parsing octal escape val=%d) fault while parsing",d);c=-1;break}a.string+=String.fromCodePoint(z);B=W=!1}else if(U)125==d?(a.string+=String.fromCodePoint(z),
B=N=U=!1):(z*=16,48<=d&&57>=d?z+=d-48:65<=d&&70>=d?z+=d-65+10:97<=d&&102>=d?z+=d-97+10:(t("(escaped character, parsing hex of \\u)",d),c=-1,B=U=!1));else{if(V||N){if(0===H&&123===d){U=!0;continue}if(2>H||N&&4>H){z*=16;if(48<=d&&57>=d)z+=d-48;else if(65<=d&&70>=d)z+=d-65+10;else if(97<=d&&102>=d)z+=d-97+10;else{t(N?"(escaped character, parsing hex of \\u)":"(escaped character, parsing hex of \\x)",d);c=-1;B=V=!1;continue}H++;N?4==H&&(a.string+=String.fromCodePoint(z),B=N=!1):2==H&&(a.string+=String.fromCodePoint(z),
B=V=!1);continue}}switch(d){case 13:ca=!0;n.col=1;continue;case 10:case 2028:case 2029:n.line++;break;case 116:a.string+="\t";break;case 98:a.string+="\b";break;case 110:a.string+="\n";break;case 114:a.string+="\r";break;case 102:a.string+="\f";break;case 48:case 49:case 50:case 51:W=!0;z=d-48;H=1;continue;case 120:V=!0;z=H=0;continue;case 117:N=!0;z=H=0;continue;default:a.string+=g}B=!1}else 92===d?B?(a.string+="\\",B=!1):B=!0:ca?(ca=!1,10==d?(n.line++,n.col=1,B=!1):(n.line++,n.col=1)):a.string+=
g}return c}function fa(){let b;for(;(b=h)<C.length;){g=C.charAt(b);let c=C.codePointAt(h++);65536<=c&&(t("fault while parsing number;",c),g+=C.charAt(h),h++);if(95!=c)if(n.col++,48<=c&&57>=c)m&&(ba=!0),a.string+=g;else if(45==c||43==c)0==a.string.length||m&&!aa&&!ba?(a.string+=g,aa=!0):(a.string+=g,J=!0);else if(58==c&&J)a.string+=g,J=!0;else if(84==c&&J)a.string+=g,J=!0;else if(90==c&&J)a.string+=g,J=!0;else if(46==c)if(r||l||m){d=!1;t("fault while parsing number;",c);break}else a.string+=g,r=!0;
else if(110==c){X=!0;break}else if(120==c||98==c||111==c||88==c||66==c||79==c)if(l||"0"!=a.string){d=!1;t("fault while parsing number;",c);break}else l=!0,a.string+=g;else if(101==c||69==c)if(m){d=!1;t("fault while parsing number;",c);break}else a.string+=g,m=!0;else{32==c||13==c||10==c||9==c||65279==c||44==c||125==c||93==c||58==c?h=b:p&&(d=!1,t("fault while parsing number;",c));break}}p||h!=C.length?(R=!1,a.value_type=5,0==k&&(E=!0)):R=!0}function ja(){let c,h=null,e={};0<b&&29>b&&A();if(0==k)29==
b||30==b?((h=u.find((b)=>b.name===a.string))?(e=Object.assign(e,h.protoObject),Object.setPrototypeOf(e,Object.getPrototypeOf(h.protoObject)),c=6):(u.push(h={name:a.string,protoObject:K[a.string]||Object.create({}),fields:[]}),c=5),b=0):(c=3,b=29);else if(29==b||30==b||1===k||4===k)0!=b?((h=u.find((b)=>b.name===a.string))||t("Referenced class "+a.string+" has not been defined",f),e=Object.assign(e,h.protoObject),Object.setPrototypeOf(e,Object.getPrototypeOf(h.protoObject)),c=6):c=3,b=0;else{if(3==
k&&0==b)return t("fault while parsing; getting field name unexpected ",f),d=!1;c=3}{let b=ha();a.value_type=6;0==k?D=y=e:4==k&&(y[a.name]=e);b.context=k;b.elements=y;b.current_class=w;b.current_class_field=F;b.arrayType=G;b.element_array=q;b.name=a.name;w=h;F=0;y=e;P||(P=y);v.push(b);O();k=c}return!0}function ka(){0<b&&29>b&&A();if(29==b){var c=oa.findIndex((b)=>b===a.string);0<=c?(b=0,G=c):"ref"===a.string?G=-2:t("Unknown type specified for array:"+a.string,f)}else if(3==k||29==b||30==b)return t("Fault while parsing; while getting field name unexpected",
f),d=!1;{c=ha();a.value_type=13;let b=[];0==k?D=q=b:4==k&&(y[a.name]=b);c.context=k;c.elements=y;c.current_class=w;c.current_class_field=F;c.arrayType=G;c.element_array=q;c.name=a.name;w=null;F=0;q=b;P||(P=elements_array);v.push(c);O();k=1}return!0}var Z=0;if(!d)return-1;if(c&&c.length){var L=la();L.buf=c;I.push(L)}else R&&(R=!1,a.value_type=5,0==k&&(E=!0),Z=1);for(;d&&(L=I.shift());){h=L.n;var C=L.buf;Q&&(c=ea(M),0>c?d=!1:0<c&&(Q=!1,d&&(a.value_type=4)));for(R&&fa();!E&&d&&h<C.length;){g=C.charAt(h);
var f=C.codePointAt(h++);65536<=f&&(g+=C.charAt(h),h++);n.col++;if(x){if(1==x){if(42==f){x=3;continue}47!=f?(t("fault while parsing;",f),d=!1):x=2;continue}if(2==x){10==f&&(x=0);continue}if(3==x){42==f&&(x=4);continue}if(4==x){47==f?x=0:42!=f&&(x=3);continue}}switch(f){case 47:x||(x=1);break;case 123:ja();break;case 91:ka();break;case 58:3==k?0!=b&&29!=b&&30!=b?(d=FALSE,thorwError(`fault while parsing; unquoted keyword used as object field name (state:${b})`,f)):(b=0,a.name=a.string,a.string="",k=
4,a.value_type=0):(1==k?t("(in array, got colon out of string):parsing fault;",f):t("(outside any object, got colon out of string):parsing fault;",f),d=!1);break;case 125:31==b&&(b=0);5==k?w?(a.string&&(w.protoObject[a.string]=void 0,w.fields.push(a.string)),O(),c=v.pop(),b=k=0,y=c.elements,q=c.element_array,w=c.current_class,F=c.current_class_field,G=c.arrayType,T.push(c)):t("State error; gathering class fields, and lost the class",f):3==k||6==k?(0!=a.value_type&&(a.name=w.fields[F++],Y()),a.value_type=
6,a.contains=y,a.string="",c=v.pop(),k=c.context,y=c.elements,q=c.element_array,w=c.current_class,F=c.current_class_field,G=c.arrayType,T.push(c),0==k&&(E=!0)):4==k?(0!=a.value_type&&Y(),a.value_type=6,a.contains=y,c=v.pop(),a.name=c.name,k=c.context,y=c.elements,w=c.current_class,F=c.current_class_field,G=c.arrayType,q=c.element_array,T.push(c),0==k&&(E=!0)):(t("Fault while parsing; unexpected",f),d=!1);e=!1;break;case 93:31==b&&(b=0);1==k?(0!=a.value_type&&S(),a.contains=q,c=v.pop(),a.name=c.name,
k=c.context,y=c.elements,w=c.current_class,F=c.current_class_field,G=c.arrayType,q=c.element_array,T.push(c),a.value_type=13,0==k&&(E=!0)):(t(`bad context ${k}; fault while parsing`,f),d=!1);e=!1;break;case 44:if(31==b||29==b)b=0;5==k?w?(w.protoObject[a.string]=void 0,w.fields.push(a.string),a.string="",b=29):t("State error; gathering class fields, and lost the class",f):3==k?w?(a.name=w.fields[F++],0!=a.value_type&&(Y(),O())):t("State error; gathering class values, and lost the class",f):6==k?w?
(a.name=w.fields[F++],0!=a.value_type&&(Y(),O())):t("State error; gathering class values, and lost the class",f):1==k?(0==a.value_type&&(a.value_type=12),0!=a.value_type&&(S(),O())):4==k?(k=3,0!=a.value_type&&(Y(),O())):(d=!1,t("bad context; excessive commas while parsing;",f));e=!1;break;default:if(0==k||4==k&&29==b||3==k||5==k)switch(f){case 96:case 34:case 39:0==b||29==b?ea(f)?a.value_type=4:(M=f,Q=!0):t("fault while parsing; quote not at start of field name",f);break;case 10:n.line++,n.col=1;
case 13:case 32:case 9:case 65279:if(31===b){b=0;0===k&&(E=!0);break}0!==b&&30!==b&&(29===b?a.string.length&&(b=30):(d=!1,t("fault while parsing; whitepsace unexpected",f)));break;default:0==b&&(48<=f&&57>=f||43==f||46==f||45==f)?(r=ba=aa=X=J=m=l=!1,a.string=g,L.n=h,fa()):(30===b&&(d=!1,t("fault while parsing; character unexpected",f)),0===b&&(b=29),a.string+=g)}else switch(f){case 96:case 34:case 39:ea(f)?(a.value_type=4,b=31):(M=f,Q=!0);break;case 10:n.line++,n.col=1;case 32:case 9:case 13:case 65279:if(31==
b){b=0;0==k&&(E=!0);break}0!=b&&30!=b&&(29==b?a.string.length&&(b=30):(d=!1,t("fault parsing whitespace",f)));break;case 116:0==b?b=1:27==b?b=28:A(f);break;case 114:1==b?b=2:A(f);break;case 117:2==b?b=3:9==b?b=10:0==b?b=12:A(f);break;case 101:3==b?(a.value_type=2,b=31):8==b?(a.value_type=3,b=31):14==b?b=15:18==b?b=19:A(f);break;case 110:0==b?b=9:12==b?b=13:17==b?b=18:22==b?b=23:25==b?b=26:A(f);break;case 100:13==b?b=14:19==b?(a.value_type=-1,b=31):A(f);break;case 105:16==b?b=17:24==b?b=25:26==b?b=
27:A(f);break;case 108:10==b?b=11:11==b?(a.value_type=1,b=31):6==b?b=7:A(f);break;case 102:0==b?b=5:15==b?b=16:23==b?b=24:A(f);break;case 97:5==b?b=6:20==b?b=21:A(f);break;case 115:7==b?b=8:A(f);break;case 73:0==b?b=22:A(f);break;case 78:0==b?b=20:21==b?(a.value_type=e?7:8,b=31):A(f);break;case 121:28==b?(a.value_type=e?9:10,b=31):A(f);break;case 45:0==b?e=!e:A(f);break;default:0==b&&(48<=f&&57>=f||43==f||46==f||45==f)?(r=ba=aa=X=J=m=l=!1,a.string=g,L.n=h,fa()):A(f)}}if(E){31==b&&(b=0);break}}h==
C.length?(ia.push(L),Q||R||3==k?Z=0:0!=k||0==a.value_type&&!D||(E=!0,Z=1)):(L.n=h,I.unshift(L),Z=2);if(E)break}if(!d)return-1;E&&0!=a.value_type&&(D=da(),e=!1,a.string="",a.value_type=0);E=!1;P=null;return Z}}};const S=[Object.freeze(JSOX.begin())];var sa=0;JSOX.parse=function(c,p){var a=sa++;S.length<=a&&S.push(Object.freeze(JSOX.begin()));a=S[a];"string"!==typeof c&&(c=String(c));a.reset();if(0<a._write(c,!0))return c=a.value(),"function"===typeof p&&function b(a,c){var d,e=a[c];if(e&&"object"===
typeof e)for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)){var h=b(e,d);void 0!==h?e[d]=h:delete e[d]}return p.call(a,c,e)}({"":c},""),c};var K=new WeakMap,u=function(){console.log("this:",this,"valueof:",this.valueOf());return this.valueOf()};K.set(Date.prototype,function(){var c=-this.getTimezoneOffset(),p=0<=c?"+":"-",a=function(a){a=Math.floor(Math.abs(a));return(10>a?"0":"")+a};return this.getFullYear()+"-"+a(this.getMonth()+1)+"-"+a(this.getDate())+"T"+a(this.getHours())+":"+a(this.getMinutes())+
":"+a(this.getSeconds())+p+a(c/60)+":"+a(c%60)});K.set(Boolean.prototype,u);K.set(Number.prototype,u);K.set(String.prototype,u);K.set(BigInt.prototype,function(){return this+"n"});JSOX.registerToJSOX=function(c,p){K.set(c,p)};JSOX.stringifier=function(){function c(a){if(null!==a){var c=g.get(a);if(c)return c;g.set(a,JSON.stringify(b))}}function p(a,b){if(b){b.map((a)=>{if("string"===typeof a)return a});var c=b.toString()}else c=Object.keys(a).toString();return n.find((a)=>{if(a.tag===c)return!0})}
function a(a,e,g){function d(a){return"true false null NaN Infinity undefined".split(" ").find((b)=>b===a)||a.includes(" ")?h+JSOX.escape(a)+h:a}function y(a,e){var g,k=q,x=b.length,l=e[a];var r=l&&K.get(Object.getPrototypeOf(l));if(l&&("object"===typeof l||"bigint"===typeof l)&&"function"===typeof r)return"function"===typeof v?v.call(e,a,r.call(l,a),l):r.call(l,a);"function"===typeof v&&(l=v.call(e,a,l));switch(typeof l){case "string":return h+JSOX.escape(l)+h;case "number":return isNaN(l)?"NaN":
isFinite(l)?String(l):0>l?-Infinity:Infinity;case "boolean":case "null":return String(l);case "object":if(g=c(l))return"ref"+g;if(!l)return"null";q+=D;r=null;e=[];var m=Object.prototype.toString.apply(l);r=null;"[object Uint8Array]"===m?(r=l.buffer,m="u8"):"[object Uint16Array]"===m?(r=l.buffer,m="u16"):"[object Uint32Array]"===m?(r=l.buffer,m="u32"):"[object Int8Array]"===m?(r=l.buffer,m="s8"):"[object Int16Array]"===m?(r=l.buffer,m="s16"):"[object Int32Array]"===m?(r=l.buffer,m="s32"):"[object Float32Array]"===
m?(r=l.buffer,m="f32"):"[object Float64Array]"===m?(r=l.buffer,m="f64"):"[object Uint8ClampedArray]"===m?(r=l.buffer,m="uc8"):"[object ArrayBuffer]"===m&&(r=l,m="ab");if(r)return g=m+"["+ma(r)+"]";if("[object Array]"===m){var w=l.length;for(m=0;m<w;m+=1)b[x]=m,e[m]=y(m,l)||"null",b.splice(x,1);a=""===a?n.map((a)=>a.name+"{"+a.fields.join(",")+"}").join(q?"\n":"")+(q?"\n":""):"";g=a+(0===e.length?"[]":q?"[\n"+q+e.join(",\n"+q)+"\n"+k+"]":"["+e.join(",")+"]");q=k;return g}if(v&&"object"===typeof v)for(w=
v.length,r=p(l,v),m=0;m<w;m+=1){if("string"===typeof v[m]){var u=v[m];b[x]=u;g=y(u,l);b.splice(x,1);g&&(r?e.push(g):e.push(d(u)+(q?": ":":")+g))}}else for(u in r=p(l),l)Object.prototype.hasOwnProperty.call(l,u)&&(b[x]=u,g=y(u,l),b.splice(x,1),g&&(r?e.push(g):e.push(d(u)+(q?": ":":")+g)));a=""===a?n.map((a)=>a.name+"{"+a.fields.join(",")+"}").join(q?"\n":"")+(q?"\n":""):"";g=a+(0===e.length?"{}":q?(r?d(r.name):"")+"{\n"+q+e.join(",\n"+q)+"\n"+k+"}":(r?d(r.name):"")+"{"+e.join(",")+"}");q=k;return g}}
if(void 0===a)return"undefined";if(null!==a){var q,v,u;var D=q="";if("number"===typeof g)for(u=0;u<g;u+=1)D+=" ";else"string"===typeof g&&(D=g);if((v=e)&&"function"!==typeof e&&("object"!==typeof e||"number"!==typeof e.length))throw Error("JSOX.stringify");return y("",{"":a})}}var n=[],h='"',g=new WeakMap,b=[];return{defineClass(a,b){n.push({name:a,tag:Object.keys(b).toString(),fields:Object.keys(b)})},stringify(b,c,g){return a(b,c,g)},setQuote(a){h=a}}};const M={"=":-1};for(u=0;256>u;u++)64>u&&(M["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[u]]=
u);JSOX.stringify=function(c,p,a){return JSOX.stringifier().stringify(c,p,a)}}privateizeEverything();
