var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,f){b!=Array.prototype&&b!=Object.prototype&&(b[d]=f.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,d,f,n){if(d){f=$jscomp.global;b=b.split(".");for(n=0;n<b.length-1;n++){var e=b[n];e in f||(f[e]={});f=f[e]}b=b[b.length-1];n=f[b];d=d(n);d!=n&&null!=d&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.fromCodePoint",function(b){return b?b:function(b){for(var d="",n=0;n<arguments.length;n++){var e=Number(arguments[n]);if(0>e||1114111<e||e!==Math.floor(e))throw new RangeError("invalid_code_point "+e);65535>=e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(e>>>10&1023|55296),d+=String.fromCharCode(e&1023|56320))}return d}},"es6","es3");
$jscomp.checkStringArgs=function(b,d,f){if(null==b)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.codePointAt",function(b){return b?b:function(b){var d=$jscomp.checkStringArgs(this,null,"codePointAt"),n=d.length;b=Number(b)||0;if(0<=b&&b<n){b|=0;var e=d.charCodeAt(b);if(55296>e||56319<e||b+1===n)return e;b=d.charCodeAt(b+1);return 56320>b||57343<b?e:1024*(e-55296)+b+9216}}},"es6","es3");$jscomp.findInternal=function(b,d,f){b instanceof String&&(b=String(b));for(var n=b.length,e=0;e<n;e++){var M=b[e];if(d.call(f,M,e,b))return{i:e,v:M}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6","es3");$jscomp.owns=function(b,d){return Object.prototype.hasOwnProperty.call(b,d)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,d){for(var f=1;f<arguments.length;f++){var n=arguments[f];if(n)for(var e in n)$jscomp.owns(n,e)&&(b[e]=n[e])}return b};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");
$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},d={};try{return d.__proto__=b,d.a}catch(f){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,d){b.__proto__=d;if(b.__proto__!==d)throw new TypeError(b+" is not extensible");return b}:null;$jscomp.polyfill("Object.setPrototypeOf",function(b){return b||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.polyfill("Array.prototype.findIndex",function(b){return b?b:function(b,f){return $jscomp.findInternal(this,b,f).i}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},d=Object.create(new $jscomp.global.Proxy(b,{get:function(f,n,e){return f==b&&"q"==n&&e==d}}));return!0===d.q}catch(f){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var d=b[Symbol.iterator];return d?d.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill("WeakMap",function(b){function d(){if(!b||!Object.seal)return!1;try{var d=Object.seal({}),e=Object.seal({}),f=new b([[d,2],[e,3]]);if(2!=f.get(d)||3!=f.get(e))return!1;f["delete"](d);f.set(e,4);return!f.has(d)&&4==f.get(e)}catch(I){return!1}}function f(b){$jscomp.owns(b,e)||$jscomp.defineProperty(b,e,{value:{}})}function n(b){var d=Object[b];d&&(Object[b]=function(b){f(b);return d(b)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(d())return b;
var e="$jscomp_hidden_"+Math.random();n("freeze");n("preventExtensions");n("seal");var M=0,N=function(b){this.id_=(M+=Math.random()+1).toString();if(b){$jscomp.initSymbol();$jscomp.initSymbolIterator();b=$jscomp.makeIterator(b);for(var d;!(d=b.next()).done;)d=d.value,this.set(d[0],d[1])}};N.prototype.set=function(b,d){f(b);if(!$jscomp.owns(b,e))throw Error("WeakMap key fail: "+b);b[e][this.id_]=d;return this};N.prototype.get=function(b){return $jscomp.owns(b,e)?b[e][this.id_]:void 0};N.prototype.has=
function(b){return $jscomp.owns(b,e)&&$jscomp.owns(b[e],this.id_)};N.prototype["delete"]=function(b){return $jscomp.owns(b,e)&&$jscomp.owns(b[e],this.id_)?delete b[e][this.id_]:!1};return N},"es6","es3");$jscomp.iteratorFromArray=function(b,d){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var f=0,n={next:function(){if(f<b.length){var e=f++;return{value:d(e,b[e]),done:!1}}n.next=function(){return{done:!0,value:void 0}};return n.next()}};n[Symbol.iterator]=function(){return n};return n};
$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(b,f){return b===f?0!==b||1/b===1/f:b!==b&&f!==f}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,f){var d=this;d instanceof String&&(d=String(d));for(var e=d.length,M=f||0;M<e;M++)if(d[M]==b||Object.is(d[M],b))return!0;return!1}},"es7","es3");
$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,f){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,f||0)}},"es6","es3");var JSOX="object"===typeof exports?exports:{};
function privateizeEverything(){function b(){var b=N.pop();b||(b={context:0,current_class:null,current_class_field:0,arrayType:-1,elements:null,element_array:null});return b}function d(){var b=na.pop();b?b.n=0:b={buf:null,n:0};return b}function f(b){var d="";b=new Uint8Array(b);var a=b.byteLength,e=a%3;a-=e;for(var f,m,p,c,l=0;l<a;l+=3)c=b[l]<<16|b[l+1]<<8|b[l+2],f=(c&16515072)>>18,m=(c&258048)>>12,p=(c&4032)>>6,c&=63,d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[c];1==e?(c=b[a],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(c&252)>>2]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(c&3)<<4]+"=="):2==e&&(c=b[a]<<8|b[a+1],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(c&64512)>>10]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(c&1008)>>
4]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(c&15)<<2]+"=");return d}function n(b){var d=new ArrayBuffer(3*(b.length+3>>2|0)-(("="===b[b.length-1]?1:0)+("="===b[b.length-2]?1:0))),a=new Uint8Array(d),e,f=b.length+3>>2;for(e=0;e<f;e++){var m=T[b[4*e+1]],p=T[b[4*e+2]],c=T[b[4*e+3]];a[3*e]=T[b[4*e]]<<2|m>>4;0<=p&&(a[3*e+1]=m<<4|p>>2&15);0<=c&&(a[3*e+2]=p<<6|c&63)}return d}var e="ab u8 cu8 s8 u16 s16 u32 s32 u64 s64 f32 f64".split(" "),M=[ArrayBuffer,Uint8Array,Uint8ClampedArray,
Int8Array,Uint16Array,Int16Array,Uint32Array,Int32Array,null,null,Float32Array,Float32Array],N=[],na=[];JSOX.escape=function(b){var d,a="";if(!b)return b;for(d=0;d<b.length;d++){if('"'==b[d]||"\\"==b[d]||"`"==b[d]||"'"==b[d])a+="\\";a+=b[d]}return a};JSOX.begin=function(f,ba){var a={name:null,value_type:0,string:"",contains:null},W=1,Q=1,m=0,p,c=0,l=!0,B=!1,R=null,Y=null,t=void 0,w=[],z={first:null,last:null,saved:null,push:function(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=null,b.prior=
this.last):b={node:a,next:null,prior:this.last};this.last||(this.first=b);this.last=b;this.length++},pop:function(){var a=this.last;if(!a)return null;(this.last=a.prior)||(this.first=null);a.next=this.saved;this.saved=a;this.length--;return a.node},length:0},D=[],ka={},x=null,J=0,K=-1,k=0,g=0,y=!1,q=!1,u=!1,I=!1,E=!1,O={first:null,last:null,saved:null,push:function(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=null,b.prior=this.last):b={node:a,next:null,prior:this.last};this.last||(this.first=
b);this.last=b},shift:function(){var a=this.first;if(!a)return null;(this.first=a.next)||(this.last=null);a.next=this.saved;this.saved=a;return a.node},unshift:function(a){var b=this.saved;b?(this.saved=b.next,b.node=a,b.next=this.first,b.prior=null):b={node:a,next:this.first,prior:null};this.first||(this.last=b);this.first=b}},T=null,Z=!1,aa=!1,F=!1,ja=!1,ca=!1,U=!1,da=!1,A=0,L=0,ea=!1,H=!1,P=!1,fa=!1;return{value:function(){var a=R;R=void 0;return a},reset:function(){c=0;l=!0;O.last&&(O.last.next=
O.save);O.save=O.first;O.first=O.last=null;z.last&&(z.last.next=z.save);z.save=O.first;w=z.first=z.last=null;t=void 0;k=0;D=[];ka={};x=null;J=0;a.value_type=0;a.name=null;a.string="";Q=W=1;B=!1;g=0;ja=F=Z=H=!1},usePrototype:function(a,b){ka[a]=b},write:function(a){"string"!==typeof a&&(a=String(a));for(a=this._write(a,!1);0<a&&!(R&&("function"===typeof ba&&function ta(a,b){var c,d=a[b];if(d&&"object"===typeof d)for(c in d)if(Object.prototype.hasOwnProperty.call(d,c)){var e=ta(d,c);void 0!==e?d[c]=
e:delete d[c]}return ba.call(a,b,d)}({"":R},""),f(R),R=void 0),2>a);a=this._write());},_write:function(f,ba){function v(a,b){throw Error(a+" '"+String.fromCodePoint(b)+"' unexpected at "+m+" (near '"+G.substr(4<m?m-4:0,4<m?3:m-1)+"["+String.fromCodePoint(b)+"]"+G.substr(m,10)+"') ["+W+":"+Q+"]");}function X(){a.value_type=0;a.string=""}function sa(a){return fa?BigInt(a):P?new Date(a):1<a.length&&!y&&!q&&!u&&48===a.charCodeAt(0)?(B?-1:1)*Number("0o"+a):(B?-1:1)*Number(a)}function V(){switch(a.value_type){case 5:return fa?
BigInt(a.string):P?new Date(a.string):sa(a.string);case 4:return a.string;case 2:return!0;case 3:return!1;case 7:return NaN;case 8:return NaN;case 9:return-Infinity;case 10:return Infinity;case 1:return null;case -1:break;case 12:break;case 6:return a.contains;case 13:if(0<=K){var b=n(a.string);return 0===K?b:new M[K](b)}if(-2===K){var c=Y;a.contains.forEach(function(a){return c=c[a]});return c}return a.contains;default:console.log("Unhandled value conversion.",a)}}function oa(){switch(a.value_type){case 12:w.push(void 0);
delete w[w.length-1];break;default:w.push(V())}}function ha(){12!==a.value_type&&(t[a.name]=V())}function C(b){B&&(valstring+="-",B=!1);switch(c){case 31:switch(a.value_type){case 2:a.string+="true";break;case 3:a.string+="false";break;case 1:a.string+="null";break;case 10:a.string+="Infinity";break;case 9:a.string+="-Infinity";break;case 8:a.string+="NaN";break;case 7:a.string+="-NaN";break;case -1:a.string+="undefined";break;default:console.log("Value of type "+a.value_type+" is not restored...")}case 1:a.string+=
"t";break;case 2:a.string+="tr";break;case 3:a.string+="tru";break;case 5:a.string+="f";break;case 6:a.string+="fa";break;case 7:a.string+="fal";break;case 8:a.string+="fals";break;case 9:a.string+="n";break;case 10:a.string+="nu";break;case 11:a.string+="nul";break;case 12:a.string+="u";break;case 13:a.string+="un";break;case 14:a.string+="und";break;case 15:a.string+="unde";break;case 16:a.string+="undef";break;case 17:a.string+="undefi";break;case 18:a.string+="undefin";break;case 19:a.string+=
"undefine";break;case 20:a.string+="Ma";break;case 21:a.string+="NaN";break;case 22:a.string+="I";break;case 23:a.string+="In";break;case 24:a.string+="Inf";break;case 25:a.string+="Infi";break;case 26:a.string+="Infin";break;case 27:a.string+="Infini";break;case 28:a.string+="Infinit"}c=29;123==b?pa():91==b?qa():32!=b&&13!=b&&10!=b&&9!=b&&65279!=b&&(44==b||125==b||93==b||58==b?v("Invalid character near identifier",b):a.string+=p)}function la(b){for(var c=0;0==c&&m<G.length;){p=G.charAt(m);var d=
G.codePointAt(m++);65536<=d&&(p+=G.charAt(m),m++);Q++;if(d==b)F?(a.string+=p,F=!1):(ea?v("Incomplete Octal sequence",d):da?v("Incomplete hexidecimal sequence",d):U?v("Incomplete unicode sequence",d):ca&&v("Incomplete long unicode sequence",d),c=1);else if(F)if(ea)if(3>L&&48<=d&&57>=d)A*=8,A+=d-48,L++,3===L&&(a.string+=String.fromCodePoint(A),F=ea=!1);else{if(255<A){v("(escaped character, parsing octal escape val=%d) fault while parsing",d);c=-1;break}a.string+=String.fromCodePoint(A);F=ea=!1}else if(ca)125==
d?(a.string+=String.fromCodePoint(A),F=U=ca=!1):(A*=16,48<=d&&57>=d?A+=d-48:65<=d&&70>=d?A+=d-65+10:97<=d&&102>=d?A+=d-97+10:(v("(escaped character, parsing hex of \\u)",d),c=-1,F=ca=!1));else{if(da||U){if(0===L&&123===d){ca=!0;continue}if(2>L||U&&4>L){A*=16;if(48<=d&&57>=d)A+=d-48;else if(65<=d&&70>=d)A+=d-65+10;else if(97<=d&&102>=d)A+=d-97+10;else{v(U?"(escaped character, parsing hex of \\u)":"(escaped character, parsing hex of \\x)",d);c=-1;F=da=!1;continue}L++;U?4==L&&(a.string+=String.fromCodePoint(A),
F=U=!1):2==L&&(a.string+=String.fromCodePoint(A),F=da=!1);continue}}switch(d){case 13:ja=!0;Q=1;continue;case 10:case 2028:case 2029:W++;break;case 116:a.string+="\t";break;case 98:a.string+="\b";break;case 110:a.string+="\n";break;case 114:a.string+="\r";break;case 102:a.string+="\f";break;case 48:case 49:case 50:case 51:ea=!0;A=d-48;L=1;continue;case 120:da=!0;A=L=0;continue;case 117:U=!0;A=L=0;continue;default:a.string+=p}F=!1}else 92===d?F?(a.string+="\\",F=!1):F=!0:ja?(ja=!1,10==d?(W++,Q=1,F=
!1):(W++,Q=1)):a.string+=p}return c}function ma(){for(var b;(b=m)<G.length;){p=G.charAt(b);var c=G.codePointAt(m++);65536<=c&&(v("fault while parsing number;",c),p+=G.charAt(m),m++);if(95!=c)if(Q++,48<=c&&57>=c)u&&(E=!0),a.string+=p;else if(45==c||43==c)0==a.string.length||u&&!I&&!E?(a.string+=p,I=!0):(a.string+=p,P=!0);else if(58==c&&P)a.string+=p,P=!0;else if(84==c&&P)a.string+=p,P=!0;else if(90==c&&P)a.string+=p,P=!0;else if(46==c)if(q||y||u){l=!1;v("fault while parsing number;",c);break}else a.string+=
p,q=!0;else if(110==c){fa=!0;break}else if(120==c||98==c||111==c||88==c||66==c||79==c)if(y||"0"!=a.string){l=!1;v("fault while parsing number;",c);break}else y=!0,a.string+=p;else if(101==c||69==c)if(u){l=!1;v("fault while parsing number;",c);break}else a.string+=p,u=!0;else{32==c||13==c||10==c||9==c||65279==c||44==c||125==c||93==c||58==c?m=b:ba&&(l=!1,v("fault while parsing number;",c));break}}ba||m!=G.length?(aa=!1,a.value_type=5,0==k&&(H=!0)):aa=!0}function pa(){var d=null,e={};0<c&&29>c&&C();
if(0==k)if(29==c||30==c){if(d=D.find(function(b){return b.name===a.string})){e=Object.assign(e,d.protoObject);Object.setPrototypeOf(e,Object.getPrototypeOf(d.protoObject));var f=6}else D.push(d={name:a.string,protoObject:ka[a.string]||Object.create({}),fields:[]}),f=5;c=0}else f=3,c=29;else if(29==c||30==c||1===k||4===k)0!=c?((d=D.find(function(b){return b.name===a.string}))||v("Referenced class "+a.string+" has not been defined",h),e=Object.assign(e,d.protoObject),Object.setPrototypeOf(e,Object.getPrototypeOf(d.protoObject)),
f=6):f=3,c=0;else{if(3==k&&0==c)return v("fault while parsing; getting field name unexpected ",h),l=!1;f=3}var g=b();a.value_type=6;0==k?R=t=e:4==k&&(t[a.name]=e);g.context=k;g.elements=t;g.current_class=x;g.current_class_field=J;g.arrayType=K;g.element_array=w;g.name=a.name;x=d;J=0;t=e;Y||(Y=t);z.push(g);X();k=f;return!0}function qa(){0<c&&29>c&&C();if(29==c){var d=e.findIndex(function(b){return b===a.string});0<=d?(c=0,K=d):"ref"===a.string?K=-2:v("Unknown type specified for array:"+a.string,h)}else if(3==
k||29==c||30==c)return v("Fault while parsing; while getting field name unexpected",h),l=!1;d=b();a.value_type=13;var f=[];0==k?R=w=f:4==k&&(t[a.name]=f);d.context=k;d.elements=t;d.current_class=x;d.current_class_field=J;d.arrayType=K;d.element_array=w;d.name=a.name;x=null;J=0;w=f;Y||(Y=elements_array);z.push(d);X();k=1;return!0}var ia=0;if(!l)return-1;if(f&&f.length){var S=d();S.buf=f;O.push(S)}else aa&&(aa=!1,a.value_type=5,0==k&&(H=!0),ia=1);for(;l&&(S=O.shift());){m=S.n;var G=S.buf;if(Z){var r=
la(T);0>r?l=!1:0<r&&(Z=!1,l&&(a.value_type=4))}for(aa&&ma();!H&&l&&m<G.length;){p=G.charAt(m);var h=G.codePointAt(m++);65536<=h&&(p+=G.charAt(m),m++);Q++;if(g){if(1==g){if(42==h){g=3;continue}47!=h?(v("fault while parsing;",h),l=!1):g=2;continue}if(2==g){10==h&&(g=0);continue}if(3==g){42==h&&(g=4);continue}if(4==g){47==h?g=0:42!=h&&(g=3);continue}}switch(h){case 47:g||(g=1);break;case 123:pa();break;case 91:qa();break;case 58:3==k?0!=c&&29!=c&&30!=c?(l=FALSE,thorwError("fault while parsing; unquoted keyword used as object field name (state:"+
c+")",h)):(c=0,a.name=a.string,a.string="",k=4,a.value_type=0):(1==k?v("(in array, got colon out of string):parsing fault;",h):v("(outside any object, got colon out of string):parsing fault;",h),l=!1);break;case 125:31==c&&(c=0);5==k?x?(a.string&&(x.protoObject[a.string]=void 0,x.fields.push(a.string)),X(),r=z.pop(),c=k=0,t=r.elements,w=r.element_array,x=r.current_class,J=r.current_class_field,K=r.arrayType,N.push(r)):v("State error; gathering class fields, and lost the class",h):3==k||6==k?(0!=a.value_type&&
(a.name=x.fields[J++],ha()),a.value_type=6,a.contains=t,a.string="",r=z.pop(),k=r.context,t=r.elements,w=r.element_array,x=r.current_class,J=r.current_class_field,K=r.arrayType,N.push(r),0==k&&(H=!0)):4==k?(0!=a.value_type&&ha(),a.value_type=6,a.contains=t,r=z.pop(),a.name=r.name,k=r.context,t=r.elements,x=r.current_class,J=r.current_class_field,K=r.arrayType,w=r.element_array,N.push(r),0==k&&(H=!0)):(v("Fault while parsing; unexpected",h),l=!1);B=!1;break;case 93:31==c&&(c=0);1==k?(0!=a.value_type&&
oa(),a.contains=w,r=z.pop(),a.name=r.name,k=r.context,t=r.elements,x=r.current_class,J=r.current_class_field,K=r.arrayType,w=r.element_array,N.push(r),a.value_type=13,0==k&&(H=!0)):(v("bad context "+k+"; fault while parsing",h),l=!1);B=!1;break;case 44:if(31==c||29==c)c=0;5==k?x?(x.protoObject[a.string]=void 0,x.fields.push(a.string),a.string="",c=29):v("State error; gathering class fields, and lost the class",h):3==k?x?(a.name=x.fields[J++],0!=a.value_type&&(ha(),X())):v("State error; gathering class values, and lost the class",
h):6==k?x?(a.name=x.fields[J++],0!=a.value_type&&(ha(),X())):v("State error; gathering class values, and lost the class",h):1==k?(0==a.value_type&&(a.value_type=12),0!=a.value_type&&(oa(),X())):4==k?(k=3,0!=a.value_type&&(ha(),X())):(l=!1,v("bad context; excessive commas while parsing;",h));B=!1;break;default:if(0==k||4==k&&29==c||3==k||5==k)switch(h){case 96:case 34:case 39:0==c||29==c?la(h)?a.value_type=4:(T=h,Z=!0):v("fault while parsing; quote not at start of field name",h);break;case 10:W++,
Q=1;case 13:case 32:case 9:case 65279:if(31===c){c=0;0===k&&(H=!0);break}0!==c&&30!==c&&(29===c?a.string.length&&(c=30):(l=!1,v("fault while parsing; whitepsace unexpected",h)));break;default:0==c&&(48<=h&&57>=h||43==h||46==h||45==h)?(q=E=I=fa=P=u=y=!1,a.string=p,S.n=m,ma()):(30===c&&(l=!1,v("fault while parsing; character unexpected",h)),0===c&&(c=29),a.string+=p)}else switch(h){case 96:case 34:case 39:la(h)?(a.value_type=4,c=31):(T=h,Z=!0);break;case 10:W++,Q=1;case 32:case 9:case 13:case 65279:if(31==
c){c=0;0==k&&(H=!0);break}0!=c&&30!=c&&(29==c?a.string.length&&(c=30):(l=!1,v("fault parsing whitespace",h)));break;case 116:0==c?c=1:27==c?c=28:C(h);break;case 114:1==c?c=2:C(h);break;case 117:2==c?c=3:9==c?c=10:0==c?c=12:C(h);break;case 101:3==c?(a.value_type=2,c=31):8==c?(a.value_type=3,c=31):14==c?c=15:18==c?c=19:C(h);break;case 110:0==c?c=9:12==c?c=13:17==c?c=18:22==c?c=23:25==c?c=26:C(h);break;case 100:13==c?c=14:19==c?(a.value_type=-1,c=31):C(h);break;case 105:16==c?c=17:24==c?c=25:26==c?c=
27:C(h);break;case 108:10==c?c=11:11==c?(a.value_type=1,c=31):6==c?c=7:C(h);break;case 102:0==c?c=5:15==c?c=16:23==c?c=24:C(h);break;case 97:5==c?c=6:20==c?c=21:C(h);break;case 115:7==c?c=8:C(h);break;case 73:0==c?c=22:C(h);break;case 78:0==c?c=20:21==c?(a.value_type=B?7:8,c=31):C(h);break;case 121:28==c?(a.value_type=B?9:10,c=31):C(h);break;case 45:0==c?B=!B:C(h);break;default:0==c&&(48<=h&&57>=h||43==h||46==h||45==h)?(q=E=I=fa=P=u=y=!1,a.string=p,S.n=m,ma()):C(h)}}if(H){31==c&&(c=0);break}}m==G.length?
(na.push(S),Z||aa||3==k?ia=0:0!=k||0==a.value_type&&!R||(H=!0,ia=1)):(S.n=m,O.unshift(S),ia=2);if(H)break}if(!l)return-1;H&&0!=a.value_type&&(R=V(),B=!1,a.string="",a.value_type=0);H=!1;Y=null;return ia}}};var V=[Object.freeze(JSOX.begin())],ra=0;JSOX.parse=function(b,d){var a=ra++;V.length<=a&&V.push(Object.freeze(JSOX.begin()));a=V[a];"string"!==typeof b&&(b=String(b));a.reset();if(0<a._write(b,!0))return a=a.value(),"function"===typeof d&&function p(a,b){var c,e=a[b];if(e&&"object"===typeof e)for(c in e)if(Object.prototype.hasOwnProperty.call(e,
c)){var f=p(e,c);void 0!==f?e[c]=f:delete e[c]}return d.call(a,b,e)}({"":a},""),a};var I=new WeakMap,D=function(){console.log("this:",this,"valueof:",this.valueOf());return this.valueOf()};I.set(Date.prototype,function(){var b=-this.getTimezoneOffset(),d=0<=b?"+":"-",a=function(a){a=Math.floor(Math.abs(a));return(10>a?"0":"")+a};return this.getFullYear()+"-"+a(this.getMonth()+1)+"-"+a(this.getDate())+"T"+a(this.getHours())+":"+a(this.getMinutes())+":"+a(this.getSeconds())+d+a(b/60)+":"+a(b%60)});
I.set(Boolean.prototype,D);I.set(Number.prototype,D);I.set(String.prototype,D);I.set(BigInt.prototype,function(){return this+"n"});JSOX.registerToJSOX=function(b,d){I.set(b,d)};JSOX.stringifier=function(){function b(a){if(null!==a){var b=m.get(a);if(b)return b;m.set(a,JSON.stringify(p))}}function d(a,b){if(b){b.map(function(a){if("string"===typeof a)return a});var c=b.toString()}else c=Object.keys(a).toString();return e.find(function(a){if(a.tag===c)return!0})}function a(a,l,m){function c(a){return"true false null NaN Infinity undefined".split(" ").find(function(b){return b===
a})||a.includes(" ")?n+JSOX.escape(a)+n:a}function B(a,m){var l,x=t,k=p.length,g=m[a];var y=g&&I.get(Object.getPrototypeOf(g));if(g&&("object"===typeof g||"bigint"===typeof g)&&"function"===typeof y)return"function"===typeof w?w.call(m,a,y.call(g,a),g):y.call(g,a);"function"===typeof w&&(g=w.call(m,a,g));switch(typeof g){case "string":return n+JSOX.escape(g)+n;case "number":return isNaN(g)?"NaN":isFinite(g)?String(g):0>g?-Infinity:Infinity;case "boolean":case "null":return String(g);case "object":if(l=
b(g))return"ref"+l;if(!g)return"null";t+=D;var q=null;y=[];q=Object.prototype.toString.apply(g);var u=null;"[object Uint8Array]"===q?(u=g.buffer,q="u8"):"[object Uint16Array]"===q?(u=g.buffer,q="u16"):"[object Uint32Array]"===q?(u=g.buffer,q="u32"):"[object Int8Array]"===q?(u=g.buffer,q="s8"):"[object Int16Array]"===q?(u=g.buffer,q="s16"):"[object Int32Array]"===q?(u=g.buffer,q="s32"):"[object Float32Array]"===q?(u=g.buffer,q="f32"):"[object Float64Array]"===q?(u=g.buffer,q="f64"):"[object Uint8ClampedArray]"===
q?(u=g.buffer,q="uc8"):"[object ArrayBuffer]"===q&&(u=g,q="ab");if(u)return l=q+"["+f(u)+"]";if("[object Array]"===q){var z=g.length;for(u=0;u<z;u+=1)p[k]=u,y[u]=B(u,g)||"null",p.splice(k,1);var E=""===a?e.map(function(a){return a.name+"{"+a.fields.join(",")+"}"}).join(t?"\n":"")+(t?"\n":""):"";l=E+(0===y.length?"[]":t?"[\n"+t+y.join(",\n"+t)+"\n"+x+"]":"["+y.join(",")+"]");t=x;return l}if(w&&"object"===typeof w)for(z=w.length,q=d(g,w),u=0;u<z;u+=1)"string"===typeof w[u]&&(E=w[u],p[k]=E,l=B(E,g),
p.splice(k,1),l&&(q?y.push(l):y.push(c(E)+(t?": ":":")+l)));else for(E in q=d(g),g)Object.prototype.hasOwnProperty.call(g,E)&&(p[k]=E,l=B(E,g),p.splice(k,1),l&&(q?y.push(l):y.push(c(E)+(t?": ":":")+l)));E=""===a?e.map(function(a){return a.name+"{"+a.fields.join(",")+"}"}).join(t?"\n":"")+(t?"\n":""):"";l=E+(0===y.length?"{}":t?(q?c(q.name):"")+"{\n"+t+y.join(",\n"+t)+"\n"+x+"}":(q?c(q.name):"")+"{"+y.join(",")+"}");t=x;return l}}if(void 0===a)return"undefined";if(null!==a){var t,w,z;var D=t="";if("number"===
typeof m)for(z=0;z<m;z+=1)D+=" ";else"string"===typeof m&&(D=m);if((w=l)&&"function"!==typeof l&&("object"!==typeof l||"number"!==typeof l.length))throw Error("JSOX.stringify");return B("",{"":a})}}var e=[],n='"',m=new WeakMap,p=[];return{defineClass:function(a,b){e.push({name:a,tag:Object.keys(b).toString(),fields:Object.keys(b)})},stringify:function(b,d,e){return a(b,d,e)},setQuote:function(a){n=a}}};var T={"=":-1};for(D=0;256>D;D++)64>D&&(T["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]]=
D);JSOX.stringify=function(b,d,a){return JSOX.stringifier().stringify(b,d,a)}}privateizeEverything();
